"""add file_type for income_attach

Revision ID: 275d3ce917cd
Revises: baa114fb44db
Create Date: 2025-11-20 23:28:53.941369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "275d3ce917cd"
down_revision: Union[str, Sequence[str], None] = "baa114fb44db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "income_transaction_attachments",
        sa.Column(
            "file_type",
            sa.Enum("jpg", "png", "pdf", name="file_type_enum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("income_transaction_attachments", "file_type")
    # ### end Alembic commands ###
