"""update relationship

Revision ID: 5844c255e6ac
Revises: 247b57226ac1
Create Date: 2025-11-20 21:10:39.718160

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5844c255e6ac"
down_revision: Union[str, Sequence[str], None] = "247b57226ac1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_user_sub_plan",
        "user_subscriptions",
        "subscription_plans",
        ["plan_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_user_sub_plan", "user_subscriptions", type_="foreignkey")
    # ### end Alembic commands ###
