"""add users.status

Revision ID: 651aecc34f5c
Revises: 275d3ce917cd
Create Date: 2025-11-22 19:57:56.158405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "651aecc34f5c"
down_revision: Union[str, Sequence[str], None] = "275d3ce917cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE user_status_enum AS ENUM (
            'PENDING',
            'ACTIVATED',
            'INACTIVATED'
        );
    """)
    op.add_column(
        "users",
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVATED", "INACTIVATED", name="user_status_enum"),
            nullable=True,
        ),
    )
    op.execute("UPDATE users SET status = 'ACTIVATED';")
    op.execute("ALTER TABLE users ALTER COLUMN status SET NOT NULL;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "status")
    op.execute("DROP TYPE user_status_enum;")
    # ### end Alembic commands ###
