"""add content_type for income_attach

Revision ID: baa114fb44db
Revises: 5844c255e6ac
Create Date: 2025-11-20 23:08:10.337062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "baa114fb44db"
down_revision: Union[str, Sequence[str], None] = "5844c255e6ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "income_transaction_attachments",
        sa.Column("content_length_bytes", sa.BigInteger(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("income_transaction_attachments", "content_length_bytes")
    # ### end Alembic commands ###
